version: '3.8'

services:
  janus:
    container_name: janus
    build:
      context: .
      target: base
    ports:
      - "8000:8000"
    command: ["python", "-m", "gunicorn", "--worker-class uvicorn.workers.UvicornWorker janus.server.app:app"]
