version: '3.8'

services:
  janus:
    container_name: janus
    build:
      context: .
      target: base
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "janus.server.app:app", "--host", "0.0.0.0", "--port", "8000"]
